データベース接続エラー: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 61] Connection refused)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Cloud SQL Proxy が起動していることを確認してください。
 * Serving Flask app 'main_local'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.123.63:8080
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 126-254-817
127.0.0.1 - - [01/Jun/2025 20:56:36] "[35m[1mGET /health HTTP/1.1[0m" 500 -
127.0.0.1 - - [01/Jun/2025 20:57:31] "[35m[1mGET /health HTTP/1.1[0m" 500 -
127.0.0.1 - - [01/Jun/2025 20:58:39] "[35m[1mGET /health HTTP/1.1[0m" 500 -
127.0.0.1 - - [01/Jun/2025 20:59:08] "[35m[1mGET /health HTTP/1.1[0m" 500 -
 * Detected change in '/Users/yoshifumikoide/Desktop/myapp/main_local_env.py', reloading
データベース接続エラー: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 61] Connection refused)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Cloud SQL Proxy が起動していることを確認してください。
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 126-254-817
 * Detected change in '/Users/yoshifumikoide/Desktop/myapp/main_local_env.py', reloading
データベース接続エラー: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 61] Connection refused)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Cloud SQL Proxy が起動していることを確認してください。
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 126-254-817
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/resource_tracker.py:301: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown: {'/mp-imd6fsz1'}
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/resource_tracker.py:301: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown: {'/mp-phsd7cjf'}
  warnings.warn(
